### PR TITLE
Small CMake Fixes

### PR DESCRIPTION
**Pull request by DeveloperPaul123**
Came across some small, trivial things when setting up with CMake on Windows.

### CODE REVIEW

**Comment by smistad** [comment]
The installing test executable fix already exists in the development branch. The test data download option was set to ON by choice, do you think it should be OFF by default? I'm not sure what's most practical.

Can you change this pull request to the development branch instead of the master branch?

Thanks!

**Comment by DeveloperPaul123** [comment]
@smistad Ok I'll revert the changes and make a new PR on the development branch. 

My thought with leaving the download option OFF by default is that if it's ON by default, then users that configure the project using the cmake-gui (like myself) don't actually get a chance to turn that option off before hitting configure; which then starts the download of the test data. I think it would be better to let the user select if they want to download the test data or not. Is that reasonable?

**Comment by smistad** [comment]
Yes, I think you're right

**Comment by DeveloperPaul123** [comment]
@smistad As requested, I've created a new PR on the development branch with the small change to the data download (see #77). Closing this now in favor of the other PR.

**Pull request closed without merging**
