### PR TITLE
Small Enhancement

### PR DESCRIPTION
**Pull request by DeveloperPaul123**
Changed from for loop to a stl algorithm to find min and max of the input coordinates of a bounding box. This may also result in a small optimization.

I should also note that I tested this by running the BoundingBoxRendererTests and it passed.

### CODE REVIEW

**Comment by smistad** [comment]
I had some issues with this on ubuntu. It seg faults when compiling in release mode, but sort of works in Debug mode. This sounds like some sort of race condition. I need to investigate it further.

**Comment by DeveloperPaul123** [comment]
Ok no problem. That's not something I would expect to happen.

**Comment by DeveloperPaul123** [comment]
@smistad I made a mistake. The function should have been `std::minmax_element` not `std::minmax`. It may have been by luck that the result still worked on my machine. But fundamentally, that was the wrong algorithm. De-referencing the result from `minmax` can have bad consequences. 

So this:
````cpp
auto min_max = std::minmax(coordinates.begin(), coordinates.end());
auto minimum = *min_max.first;
auto maximum = *min_max.second;
````
Should be this:
````cpp
auto min_max = std::minmax_element(coordinates.begin(), coordinates.end());
auto minimum = *min_max.first;
auto maximum = *min_max.second;
````

I can make the change and PR again, maybe add a separate test for the bounding box? Or I can just leave it as is. Let me know.

**Comment by smistad** [comment]
After some thinking I see that this will not work for two reasons:
1) The underlying type, eigen's Vector3f, does not over load the operator <
2) We want the minimum and maximum of each component (x, y, z), not the smallest and biggest vector.

**Pull request merged**
